version: 2
updates:

  - package-ecosystem: "github-actions"
    directories:
      - "**/*" # To specify manifests in the current directory and recursive subdirectories -> https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#defining-multiple-locations-for-manifest-files
    schedule:
      interval: "daily"
    assignees:
      - "NelsonBN"
    reviewers:
      - "NelsonBN"
    commit-message:
      prefix: "build"
      include: "scope"
    target-branch: "main"

  - package-ecosystem: "nuget"
    directories:
      - "**/*" # To specify manifests in the current directory and recursive subdirectories -> https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#defining-multiple-locations-for-manifest-files
    schedule:
      interval: "daily"
    assignees:
      - "NelsonBN"
    reviewers:
      - "NelsonBN"
    commit-message:
      prefix: "build"
      include: "scope"
    target-branch: "main"

  - package-ecosystem: "dotnet-sdk"
    directories:
      - "**/*" # To specify manifests in the current directory and recursive subdirectories -> https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#defining-multiple-locations-for-manifest-files
    schedule:
      interval: "daily"
    assignees:
      - "NelsonBN"
    reviewers:
      - "NelsonBN"
    commit-message:
      prefix: "build"
      include: "scope"
    target-branch: "main"

  - package-ecosystem: "docker"
    directories:
      - "**/*" # To specify manifests in the current directory and recursive subdirectories -> https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#defining-multiple-locations-for-manifest-files
    schedule:
      interval: "daily"
    assignees:
      - "NelsonBN"
    reviewers:
      - "NelsonBN"
    commit-message:
      prefix: "build"
      include: "scope"
    target-branch: "main"

  - package-ecosystem: "docker-compose"
    directories:
      - "**/*" # To specify manifests in the current directory and recursive subdirectories -> https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#defining-multiple-locations-for-manifest-files
    schedule:
      interval: "daily"
    assignees:
      - "NelsonBN"
    reviewers:
      - "NelsonBN"
    commit-message:
      prefix: "build"
      include: "scope"
    target-branch: "main"
