{
 "title": "OpenTelemetry Collector - v20221228",
 "description": "Provides information about the status of the OpenTelemetry Collector",
 "tags": [ "opentelemetry" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "receiver",
    "label": "receiver",
    "query": {
     "query": "label_values(otelcol_receiver_accepted_metric_points, receiver)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(otelcol_process_cpu_seconds,namespace)"
    }
   },
   {
    "name": "env",
    "query": {
     "query": "label_values(otelcol_process_cpu_seconds{namespace=~\"$namespace\"},deployment_environment)"
    }
   },
   { "name": "exporter", "label": "exporter", "query": { "query": "label_values(otelsvc_exporter)" } },
   { "name": "processor", "label": "processor", "query": { "query": "label_values(processor)" } },
   {
    "name": "job",
    "query": {
     "query": "label_values(otelcol_process_cpu_seconds{namespace=~\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Receivers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spans Accepted vs Refused /Second",
   "type": "timeseries",
   "description": "Rate of spans successfully accepted vs refused per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (receiver)",
     "legendFormat": "{{receiver}} spans accepted / sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (receiver)",
     "legendFormat": "{{ receiver }} spans refused /sec"
    }
   ]
  },
  {
   "title": "Metrics Accepted vs Refused Received/Second",
   "type": "timeseries",
   "description": "Rate of metrics successfully accepted vs refused per second",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (receiver)",
     "legendFormat": "{{receiver}} accepted /sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (receiver)",
     "legendFormat": "{{ receiver }} refused / sec"
    }
   ]
  },
  {
   "title": "Logs Accepted vs Refused Received/Second",
   "type": "timeseries",
   "description": "Rate of metrics successfully accepted vs refused per second",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_log_records{ namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (receiver)",
     "legendFormat": "{{receiver}} accepted /sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points{ namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (receiver)",
     "legendFormat": "{{ receiver }} refused / sec"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spans Exported vs Failed / Second",
   "type": "timeseries",
   "description": "Rate of spans successfully exported vs Failed per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (exporter)",
     "legendFormat": "{{exporter}} sent / sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (exporter)",
     "legendFormat": "{{ exporter }} failed /sec"
    }
   ]
  },
  {
   "title": "Metrics Exported vs failed /Second",
   "type": "timeseries",
   "description": "Rate of timeseries successfully exported per second",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\", exporter=~\"$exporter\"}[1m])) by (exporter)",
     "legendFormat": "{{exporter}} sent /sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points{namespace=~\"$namespace\", deployment_environment=~\"$env\",job=~\"$job\", exporter=~\"$exporter\"}[1m])) by (exporter)",
     "legendFormat": "{{ exporter }} failed / sec"
    }
   ]
  },
  {
   "title": "Logs Exported vs failed /Second",
   "type": "timeseries",
   "description": "Rate of timeseries successfully exported per second",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_log_records{namespace=~\"$namespace\", deployment_environment=~\"$env\", exporter=~\"$exporter\", job=~\"$job\"}[1m])) by (exporter)",
     "legendFormat": "{{exporter}} sent /sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_log_records{namespace=~\"$namespace\", deployment_environment=~\"$env\", exporter=~\"$exporter\", job=~\"$job\"}[1m])) by (exporter)",
     "legendFormat": "{{ exporter }} failed / sec"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processor Spans Received, Dropped, Accepted, Refused/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_spans_received{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | received"
    },
    {
     "expr": "sum(rate(otelcol_processor_spans_dropped{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | dropped"
    },
    {
     "expr": "sum(rate(otelcol_processor_accepted_spans{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | accepted"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_spans{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | refused"
    }
   ]
  },
  {
   "title": "Processor Metric  Dropped, Accepted, Refused/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_dropped_metric_points{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | dropped"
    },
    {
     "expr": "sum(rate(otelcol_processor_accepted_metric_points{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | accepted"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_metric_points{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | refused"
    }
   ]
  },
  {
   "title": "Processor Logs Received, Dropped, Accepted, Refused/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_dropped_log_records{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | dropped"
    },
    {
     "expr": "sum(rate(otelcol_processor_accepted_log_records{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | accepted"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_log_records{namespace=~\"$namespace\", deployment_environment=~\"$env\", job=~\"$job\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | refused"
    }
   ]
  },
  {
   "title": "Batches Received vs Dropped /Second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(otelcol_processor_batch_batch_size_trigger_send{ namespace=~\"$namespace\", processor=~\"$processor\", job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{processor}} | size send"
    },
    {
     "expr": "rate(otelcol_processor_batch_timeout_trigger_send{namespace=~\"$namespace\", processor=~\"$processor\", job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{processor}} | timeout send"
    }
   ]
  },
  {
   "title": "Queued Retry Max Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(otelcol_exporter_queue_capacity{namespace=~\"$namespace\", job=~\"$job\",}) by(exporter)",
     "legendFormat": "cap: {{exporter}}"
    },
    {
     "expr": "sum(otelcol_exporter_queue_size{namespace=~\"$namespace\", job=~\"$job\"}) by(exporter)",
     "legendFormat": "size: {{exporter}}"
    }
   ]
  },
  {
   "title": "Queued Retry Processor In-queue Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(otelcol_processor_queued_retry_queue_latency_sum/ otelcol_processor_queued_retry_queue_latency_count)",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Queued Retry Processor Send Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(otelcol_processor_queued_retry_send_latency_sum/ otelcol_processor_queued_retry_send_latency_count)",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Spans per Batch (avg from rates)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_spans_received{processor=~\"$processor\"}[1m]) / rate(otelcol_processor_batches_received{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "QueuedRetry Successful vs Failed Sent/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_queued_retry_success_send{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_queued_retry_fail_send{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Successful Batches Sent Cumulative",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(otelcol_processor_queued_retry_success_send{processor=~\"$processor\"}) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Enqueued Spans Cumulative",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(otelcol_processor_spans_received{exporter=~\"$exporter\"}) by (exporter)",
     "legendFormat": "{{exporter}}"
    }
   ]
  }
 ]
}